#include <stdio.h>
#include <iostream>
#include <time.h>
#include <windows.h>
#include <string>
#include <assert.h>
#include <stack>
#include <queue>
#include <math.h>
#include <vector>
#include <cstdlib>
#include <stddef.h>
#include <hash_map>
#include <fstream>
#include <string.h>